# 程序配置，用于劫持 Chrome 系浏览器参数

[节_配置]
# 指定被劫持的浏览器“傀儡”可执行文件
程序=C:\Users\Lenovo\AppData\Local\Google\Chrome\Application\chrome_real.exe
# 附加给浏览器“傀儡”可执行文件的参数
参数=--disable-background-networking --autoplay-policy=no-user-gesture-required

# 若为真，则会弹出重定向后的命令行并将其复制到剪切板
调试=假