document.write("<div class=\"layui-header\">");
document.write("	<div class=\"layui-logo\"><a href=\"http:\/\/www.1212321.com\/\"><img id=\"logo\" src=\"img\/logo.png\" alt=\"logo.png\"\/><\/a><\/div>");
document.write("	<ul class=\"layui-nav layui-layout-left\">");
document.write("		<li class=\"layui-nav-item\"><a href=\"index.html\">首页<\/a><\/li>");
document.write("		<li class=\"layui-nav-item\">");
document.write("			<a href=\"javascript: ;\">游戏<\/a>");
document.write("			<dl class=\"layui-nav-child\">");
document.write("				<dd><a href=\"\">死神vs火影<\/a><\/dd>");
document.write("				<dd><a href=\"\">妖尾vs海贼王<\/a><\/dd>");
document.write("				<dd><a href=\"\">其他<\/a><\/dd>");
document.write("			<\/dl>");
document.write("		<\/li>");
document.write("		<li class=\"layui-nav-item\"><a href=\"download.html\">下载<\/a><\/li>");
document.write("		<li class=\"layui-nav-item\"><a href=\"terminology.html\">术语词典<\/a><\/li>");
document.write("	<\/ul>");
document.write("	<ul class=\"layui-nav layui-layout-right\">");
document.write("		<li class=\"layui-nav-item\"><a href=\"api.html\">API 文档<\/a><\/li>");
document.write("		<li class=\"layui-nav-item\"><a href=\"javascript: ;\">反馈 \/ 捐赠<\/a><\/li>");
document.write("	<\/ul>");
document.write("<\/div>");
